defaults:
  - model_checkpoint
  - early_stopping
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:02d}"
  save_last: True
  every_n_epochs: 1
  save_on_train_epoch_end: False # runs at end of validation

early_stopping:
  monitor: "val/acc5"
  mode: "max"
  stopping_threshold: 0.875  # This should get 85% top-5 test accuracy