# @package _global_

defaults:
  - _self_
  - datamodule: default
  - module: vit_s_16
  - trainer: imagenet_vit_s_16
  - logger: null
  - callbacks: null
  - paths: default
  - extras: default
  - hydra: eval
  - codecarbon: null
  - experiment: null
  - hparams_search: null
  - debug: null

# TODO Write your team name
team_name: ???
tags: ["explore", "evaluate"]

# seed for random number generators in pytorch, numpy and python.random
seed: 0

trainer:
  precision: 32

module:
  compile: false

# TODO Complete with the paths to the checkpoints you want to test
checkpoints: [
  "baseline/2026-06-23/16-24-34/checkpoints/last.ckpt",
]
