# @package _global_

defaults:
  - _self_
  - datamodule: default
  - module: vit_s_16
  - trainer: imagenet_vit_s_16
  - logger: null
  - callbacks: null
  - paths: default
  - extras: default
  - hydra: eval
  - codecarbon: null
  - experiment: null
  - hparams_search: null
  - debug: null

# TODO Write your team name
team_name: "data"
tags: ['final', 'evaluate']

# seed for random number generators in pytorch, numpy and python.random
seed: 0

trainer:
  precision: 16-mixed

module:
  compile: false

# TODO Complete with the paths to the checkpoints you want to test
checkpoints: [
  "2_phase_training_earlier_switch/2026-07-03/09-48-27/checkpoints/last.ckpt",
]
