# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - datamodule: default
  - module: vit_s_16
  - trainer: imagenet_vit_s_16
  - logger: wandb
  - callbacks: default
  - paths: default
  - extras: default
  - hydra: default
  - codecarbon: default
  - experiment: null

  # config for hyperparameter optimization
  - hparams_search: null

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

team_name: data_team       # TODO write your team name HERE
experiment_name: ??? # TODO define this in your EXPERIMENT CONFIGS
tags: ???            # TODO define this in your EXPERIMENT CONFIGS

# First tag options: data, explore, baseline, ablate, hyperparam, final, <custom tag>
# Second tag options: train, pre-train, post-train, debug, <custom tag>
# Example: ["baseline", "train"]

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 0

# some optimization
trainer:
  precision: 16-mixed

module:
  compile: True
